name = "examples-bbird-cdn"
main = "index.js"
compatibility_date = "2026-03-13"
compatibility_flags = ["nodejs_compat"]
account_id = "ac7ee4615628005dc5ba0a22f0aae2a6"

routes = [
   { pattern = "examples.bbird.live/*", zone_name = "bbird.live" },
]

[cache]
enabled = true

[exports.default]
type = "worker"

[exports.default.cache]
enabled = false

[exports.Anonymous]
type = "worker"

[exports.Anonymous.cache]
enabled = true

[vars]
ORIGIN_HOSTNAME = "main--examples--aem-sandbox.aem.live"
PUSH_INVALIDATION = "enabled"
GATED_CACHE_PATHS = "/gated-content"

[observability.logs]
enabled = true
