name: Deploy USGS Quakes Worker

on:
  push:
    branches: [main]
    paths:
      - 'workers/usgs_quakes/**/*.js'
      - 'workers/usgs_quakes/wrangler.toml'

jobs:
  deploy:
    uses: ./.github/workflows/deploy-worker.yaml
    secrets: inherit
    with:
      working-directory: workers/usgs_quakes
